/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedSearchesRouteImport } from './routes/saved-searches'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedTokenRouteImport } from './routes/shared/$token'
import { Route as TeamsIdIndexRouteImport } from './routes/teams/$id/index'
import { Route as CollectionsIdIndexRouteImport } from './routes/collections/$id/index'
import { Route as ArticleIdIndexRouteImport } from './routes/article/$id/index'
import { Route as TopicIdArticlesRouteImport } from './routes/topic/$id/articles'
import { Route as TopicIdAnalyticsRouteImport } from './routes/topic/$id/analytics'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiCronSendDigestsRouteImport } from './routes/api/cron/send-digests'
import { Route as ApiCronSendAlertsRouteImport } from './routes/api/cron/send-alerts'
import { Route as ApiCronCheckTopicsRouteImport } from './routes/api/cron/check-topics'
import { Route as ApiCronArchiveArticlesRouteImport } from './routes/api/cron/archive-articles'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFeedsTopicIdRssRouteImport } from './routes/api/feeds/topic/$id/rss'
import { Route as ApiFeedsCollectionIdRssRouteImport } from './routes/api/feeds/collection/$id/rss'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedSearchesRoute = SavedSearchesRouteImport.update({
  id: '/saved-searches',
  path: '/saved-searches',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdIndexRoute = TeamsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => TeamsRoute,
} as any)
const CollectionsIdIndexRoute = CollectionsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => CollectionsRoute,
} as any)
const ArticleIdIndexRoute = ArticleIdIndexRouteImport.update({
  id: '/article/$id/',
  path: '/article/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicIdArticlesRoute = TopicIdArticlesRouteImport.update({
  id: '/topic/$id/articles',
  path: '/topic/$id/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicIdAnalyticsRoute = TopicIdAnalyticsRouteImport.update({
  id: '/topic/$id/analytics',
  path: '/topic/$id/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSendDigestsRoute = ApiCronSendDigestsRouteImport.update({
  id: '/api/cron/send-digests',
  path: '/api/cron/send-digests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSendAlertsRoute = ApiCronSendAlertsRouteImport.update({
  id: '/api/cron/send-alerts',
  path: '/api/cron/send-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCheckTopicsRoute = ApiCronCheckTopicsRouteImport.update({
  id: '/api/cron/check-topics',
  path: '/api/cron/check-topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronArchiveArticlesRoute = ApiCronArchiveArticlesRouteImport.update({
  id: '/api/cron/archive-articles',
  path: '/api/cron/archive-articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedsTopicIdRssRoute = ApiFeedsTopicIdRssRouteImport.update({
  id: '/api/feeds/topic/$id/rss',
  path: '/api/feeds/topic/$id/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedsCollectionIdRssRoute = ApiFeedsCollectionIdRssRouteImport.update({
  id: '/api/feeds/collection/$id/rss',
  path: '/api/feeds/collection/$id/rss',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/recommendations': typeof RecommendationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/teams': typeof TeamsRouteWithChildren
  '/topics': typeof TopicsRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/shared/$token': typeof SharedTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/archive-articles': typeof ApiCronArchiveArticlesRoute
  '/api/cron/check-topics': typeof ApiCronCheckTopicsRoute
  '/api/cron/send-alerts': typeof ApiCronSendAlertsRoute
  '/api/cron/send-digests': typeof ApiCronSendDigestsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/topic/$id/analytics': typeof TopicIdAnalyticsRoute
  '/topic/$id/articles': typeof TopicIdArticlesRoute
  '/article/$id/': typeof ArticleIdIndexRoute
  '/collections/$id/': typeof CollectionsIdIndexRoute
  '/teams/$id/': typeof TeamsIdIndexRoute
  '/api/feeds/collection/$id/rss': typeof ApiFeedsCollectionIdRssRoute
  '/api/feeds/topic/$id/rss': typeof ApiFeedsTopicIdRssRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/recommendations': typeof RecommendationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/teams': typeof TeamsRouteWithChildren
  '/topics': typeof TopicsRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/shared/$token': typeof SharedTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/archive-articles': typeof ApiCronArchiveArticlesRoute
  '/api/cron/check-topics': typeof ApiCronCheckTopicsRoute
  '/api/cron/send-alerts': typeof ApiCronSendAlertsRoute
  '/api/cron/send-digests': typeof ApiCronSendDigestsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/topic/$id/analytics': typeof TopicIdAnalyticsRoute
  '/topic/$id/articles': typeof TopicIdArticlesRoute
  '/article/$id': typeof ArticleIdIndexRoute
  '/collections/$id': typeof CollectionsIdIndexRoute
  '/teams/$id': typeof TeamsIdIndexRoute
  '/api/feeds/collection/$id/rss': typeof ApiFeedsCollectionIdRssRoute
  '/api/feeds/topic/$id/rss': typeof ApiFeedsTopicIdRssRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/recommendations': typeof RecommendationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/teams': typeof TeamsRouteWithChildren
  '/topics': typeof TopicsRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/shared/$token': typeof SharedTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/archive-articles': typeof ApiCronArchiveArticlesRoute
  '/api/cron/check-topics': typeof ApiCronCheckTopicsRoute
  '/api/cron/send-alerts': typeof ApiCronSendAlertsRoute
  '/api/cron/send-digests': typeof ApiCronSendDigestsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/topic/$id/analytics': typeof TopicIdAnalyticsRoute
  '/topic/$id/articles': typeof TopicIdArticlesRoute
  '/article/$id/': typeof ArticleIdIndexRoute
  '/collections/$id/': typeof CollectionsIdIndexRoute
  '/teams/$id/': typeof TeamsIdIndexRoute
  '/api/feeds/collection/$id/rss': typeof ApiFeedsCollectionIdRssRoute
  '/api/feeds/topic/$id/rss': typeof ApiFeedsTopicIdRssRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/dashboard'
    | '/forgot-password'
    | '/recommendations'
    | '/reset-password'
    | '/saved-searches'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/teams'
    | '/topics'
    | '/unauthenticated'
    | '/shared/$token'
    | '/api/auth/$'
    | '/api/cron/archive-articles'
    | '/api/cron/check-topics'
    | '/api/cron/send-alerts'
    | '/api/cron/send-digests'
    | '/api/stripe/webhook'
    | '/topic/$id/analytics'
    | '/topic/$id/articles'
    | '/article/$id/'
    | '/collections/$id/'
    | '/teams/$id/'
    | '/api/feeds/collection/$id/rss'
    | '/api/feeds/topic/$id/rss'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/dashboard'
    | '/forgot-password'
    | '/recommendations'
    | '/reset-password'
    | '/saved-searches'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/teams'
    | '/topics'
    | '/unauthenticated'
    | '/shared/$token'
    | '/api/auth/$'
    | '/api/cron/archive-articles'
    | '/api/cron/check-topics'
    | '/api/cron/send-alerts'
    | '/api/cron/send-digests'
    | '/api/stripe/webhook'
    | '/topic/$id/analytics'
    | '/topic/$id/articles'
    | '/article/$id'
    | '/collections/$id'
    | '/teams/$id'
    | '/api/feeds/collection/$id/rss'
    | '/api/feeds/topic/$id/rss'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/dashboard'
    | '/forgot-password'
    | '/recommendations'
    | '/reset-password'
    | '/saved-searches'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/teams'
    | '/topics'
    | '/unauthenticated'
    | '/shared/$token'
    | '/api/auth/$'
    | '/api/cron/archive-articles'
    | '/api/cron/check-topics'
    | '/api/cron/send-alerts'
    | '/api/cron/send-digests'
    | '/api/stripe/webhook'
    | '/topic/$id/analytics'
    | '/topic/$id/articles'
    | '/article/$id/'
    | '/collections/$id/'
    | '/teams/$id/'
    | '/api/feeds/collection/$id/rss'
    | '/api/feeds/topic/$id/rss'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedSearchesRoute: typeof SavedSearchesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TopicsRoute: typeof TopicsRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  SharedTokenRoute: typeof SharedTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronArchiveArticlesRoute: typeof ApiCronArchiveArticlesRoute
  ApiCronCheckTopicsRoute: typeof ApiCronCheckTopicsRoute
  ApiCronSendAlertsRoute: typeof ApiCronSendAlertsRoute
  ApiCronSendDigestsRoute: typeof ApiCronSendDigestsRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  TopicIdAnalyticsRoute: typeof TopicIdAnalyticsRoute
  TopicIdArticlesRoute: typeof TopicIdArticlesRoute
  ArticleIdIndexRoute: typeof ArticleIdIndexRoute
  ApiFeedsCollectionIdRssRoute: typeof ApiFeedsCollectionIdRssRoute
  ApiFeedsTopicIdRssRoute: typeof ApiFeedsTopicIdRssRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-searches': {
      id: '/saved-searches'
      path: '/saved-searches'
      fullPath: '/saved-searches'
      preLoaderRoute: typeof SavedSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id/': {
      id: '/teams/$id/'
      path: '/$id'
      fullPath: '/teams/$id/'
      preLoaderRoute: typeof TeamsIdIndexRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/collections/$id/': {
      id: '/collections/$id/'
      path: '/$id'
      fullPath: '/collections/$id/'
      preLoaderRoute: typeof CollectionsIdIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/article/$id/': {
      id: '/article/$id/'
      path: '/article/$id'
      fullPath: '/article/$id/'
      preLoaderRoute: typeof ArticleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$id/articles': {
      id: '/topic/$id/articles'
      path: '/topic/$id/articles'
      fullPath: '/topic/$id/articles'
      preLoaderRoute: typeof TopicIdArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$id/analytics': {
      id: '/topic/$id/analytics'
      path: '/topic/$id/analytics'
      fullPath: '/topic/$id/analytics'
      preLoaderRoute: typeof TopicIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/send-digests': {
      id: '/api/cron/send-digests'
      path: '/api/cron/send-digests'
      fullPath: '/api/cron/send-digests'
      preLoaderRoute: typeof ApiCronSendDigestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/send-alerts': {
      id: '/api/cron/send-alerts'
      path: '/api/cron/send-alerts'
      fullPath: '/api/cron/send-alerts'
      preLoaderRoute: typeof ApiCronSendAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/check-topics': {
      id: '/api/cron/check-topics'
      path: '/api/cron/check-topics'
      fullPath: '/api/cron/check-topics'
      preLoaderRoute: typeof ApiCronCheckTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/archive-articles': {
      id: '/api/cron/archive-articles'
      path: '/api/cron/archive-articles'
      fullPath: '/api/cron/archive-articles'
      preLoaderRoute: typeof ApiCronArchiveArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feeds/topic/$id/rss': {
      id: '/api/feeds/topic/$id/rss'
      path: '/api/feeds/topic/$id/rss'
      fullPath: '/api/feeds/topic/$id/rss'
      preLoaderRoute: typeof ApiFeedsTopicIdRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feeds/collection/$id/rss': {
      id: '/api/feeds/collection/$id/rss'
      path: '/api/feeds/collection/$id/rss'
      fullPath: '/api/feeds/collection/$id/rss'
      preLoaderRoute: typeof ApiFeedsCollectionIdRssRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsIdIndexRoute: typeof CollectionsIdIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdIndexRoute: CollectionsIdIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface TeamsRouteChildren {
  TeamsIdIndexRoute: typeof TeamsIdIndexRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsIdIndexRoute: TeamsIdIndexRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RecommendationsRoute: RecommendationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedSearchesRoute: SavedSearchesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TopicsRoute: TopicsRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  SharedTokenRoute: SharedTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronArchiveArticlesRoute: ApiCronArchiveArticlesRoute,
  ApiCronCheckTopicsRoute: ApiCronCheckTopicsRoute,
  ApiCronSendAlertsRoute: ApiCronSendAlertsRoute,
  ApiCronSendDigestsRoute: ApiCronSendDigestsRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  TopicIdAnalyticsRoute: TopicIdAnalyticsRoute,
  TopicIdArticlesRoute: TopicIdArticlesRoute,
  ArticleIdIndexRoute: ArticleIdIndexRoute,
  ApiFeedsCollectionIdRssRoute: ApiFeedsCollectionIdRssRoute,
  ApiFeedsTopicIdRssRoute: ApiFeedsTopicIdRssRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
